namespace: gateway
domain: "api.baselinehq.cloud"
backend:
  backend:
    image: "ghcr.io/baselinehq/backend"
    tag: "sha-11efac4"
    port: 8080
  config:
    credentials_secret_name: backend-credentials
    image_pull_secret: container-registry-credentials
